---
name: Task
about: Konkrete, kleine Aufgabe
title: "[TASK] "
labels: ["type: task"]
assignees: []
---

## Beschreibung
Kurze, präzise Beschreibung.

## Schritte
- [ ] Schritt 1
- [ ] Schritt 2

## Definition of Done
- [ ] Getestet
- [ ] Dokumentiert (README/Docs)
